---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: team-a
  namespace: team-a
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/nikever/kubernetes-hello-app-tenant
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: team-a
  namespace: team-a
spec:
  interval: 1m0s
  path: ./production/
  prune: false
  serviceAccountName: team-a
  sourceRef:
    kind: GitRepository
    name: team-a

